//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickMon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;config&gt;
        ///  &lt;bizTalkGroup sqlServer=&quot;&quot; mgmtDb=&quot;BizTalkMgmtDb&quot; allReceiveLocations=&quot;True&quot; allSendPorts=&quot;True&quot; allOrchestrations=&quot;True&quot;&gt;
        ///    &lt;receiveLocations&gt;
        ///      &lt;!--&lt;receiveLocation name=&quot;&quot; /&gt;  --&gt;
        ///    &lt;/receiveLocations&gt;
        ///    &lt;sendPorts&gt;
        ///      &lt;!--&lt;sendPort name=&quot;&quot; /&gt;--&gt;
        ///    &lt;/sendPorts&gt;
        ///    &lt;orchestrations&gt;
        ///      &lt;!--&lt;orchestration name=&quot;&quot; /&gt;--&gt;
        ///    &lt;/orchestrations&gt;
        ///  &lt;/bizTalkGroup&gt;
        ///&lt;/config&gt;.
        /// </summary>
        internal static string BizTalkGroupPortsAndOrchsDefaultConfig {
            get {
                return ResourceManager.GetString("BizTalkGroupPortsAndOrchsDefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;config&gt;
        ///  &lt;bizTalkGroup sqlServer=&quot;&quot; mgmtDb=&quot;BizTalkMgmtDb&quot; instancesWarning=&quot;10&quot; instancesError=&quot;50&quot; allHostsApps=&quot;True&quot; showLastXDetails=&quot;10&quot; raiseHtmlAlerts=&quot;True&quot;&gt;
        ///    &lt;hosts /&gt;
        ///    &lt;apps /&gt;
        ///  &lt;/bizTalkGroup&gt;
        ///&lt;/config&gt;.
        /// </summary>
        internal static string BizTalkSuspendedCountCollectorDefaultConfig {
            get {
                return ResourceManager.GetString("BizTalkSuspendedCountCollectorDefaultConfig", resourceCulture);
            }
        }
    }
}
