//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickMon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;collectorEntry uniqueID=&quot;{0}&quot; name=&quot;{1}&quot; enabled=&quot;{2}&quot; isFolder=&quot;{3}&quot; collector=&quot;{4}&quot; dependOnParent=&quot;{5}&quot; collectOnParentWarning=&quot;{6}&quot; 
        ///  repeatAlertInXMin=&quot;{7}&quot; alertOnceInXMin=&quot;{8}&quot; delayErrWarnAlertForXSec=&quot;{9}&quot;
        ///  repeatAlertInXPolls=&quot;{10}&quot; alertOnceInXPolls=&quot;{11}&quot; delayErrWarnAlertForXPolls=&quot;{12}&quot;
        ///  correctiveScriptDisabled=&quot;{13}&quot; correctiveScriptOnWarningPath=&quot;{14}&quot; correctiveScriptOnErrorPath=&quot;{15}&quot; restorationScriptPath=&quot;{16}&quot; correctiveScriptsOnlyOnStateChange=&quot;{17}&quot;
        ///  enableRemoteExecute=&quot;{18 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CollectorEntryXml {
            get {
                return ResourceManager.GetString("CollectorEntryXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;monitorPack version=&quot;{0}&quot; name=&quot;{1}&quot; enabled=&quot;{2}&quot; defaultViewerNotifier=&quot;{3}&quot; runCorrectiveScripts=&quot;{4}&quot; collectorStateHistorySize=&quot;{5}&quot; pollingFreqSecOverride=&quot;{6}&quot;&gt;
        ///  &lt;collectorEntries&gt;
        ///    {7}
        ///  &lt;/collectorEntries&gt;
        ///  &lt;notifierEntries&gt;
        ///    {8}
        ///  &lt;/notifierEntries&gt;
        ///&lt;/monitorPack&gt;.
        /// </summary>
        internal static string MonitorPackXml {
            get {
                return ResourceManager.GetString("MonitorPackXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;notifierEntry name=&quot;{0}&quot; notifier=&quot;{1}&quot; enabled=&quot;{2}&quot; alertLevel=&quot;{3}&quot; detailLevel=&quot;{4}&quot;&gt;
        ///    {5}
        ///    {6}
        ///&lt;/notifierEntry&gt;.
        /// </summary>
        internal static string NotifierEntryXml {
            get {
                return ResourceManager.GetString("NotifierEntryXml", resourceCulture);
            }
        }
    }
}
