//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickMon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;config&gt;
        ///  &lt;connection sqlServer=&quot;&quot; integratedSec=&quot;True&quot; userName=&quot;&quot; password=&quot;&quot; cmndTimeOut=&quot;60&quot;&gt;
        ///      &lt;database name=&quot;&quot; warningSizeMB=&quot;1024&quot; errorSizeMB=&quot;4096&quot;/&gt;
        ///  &lt;/connection&gt;
        ///&lt;/config&gt;.
        /// </summary>
        internal static string DatabaseSizeEmptyConfig_xml {
            get {
                return ResourceManager.GetString("DatabaseSizeEmptyConfig.xml", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap doc_refresh {
            get {
                object obj = ResourceManager.GetObject("doc_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use master
        ///declare @PageSize varchar(10)
        ///select @PageSize=v.low/1024.0
        ///from master..spt_values v
        ///where v.number=1 and v.type=&apos;E&apos;
        ///
        ///select name as DatabaseName, convert(float,null) as Size
        ///into #tem
        ///From sysdatabases where dbid&gt;4 and name like &apos;&lt;Database&gt;&apos;
        ///
        ///declare @SQL varchar (8000)
        ///set @SQL=&apos;&apos;
        ///
        ///while exists (select * from #tem where size is null)
        ///begin
        ///select @SQL=&apos;update #tem set size=(select round(sum(size)*&apos;+@PageSize+&apos;/1024,0) From &apos;+quotename(databasename)+&apos;.dbo.sysfiles) where database [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectDatabaseSizesScript {
            get {
                return ResourceManager.GetString("SelectDatabaseSizesScript", resourceCulture);
            }
        }
    }
}
