//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickMon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;config&gt;
        ///  &lt;queries&gt;
        ///    &lt;!--
        ///    &lt;query name=&quot;&quot; dataSource=&quot;&quot; provider=&quot;Microsoft.Jet.OLEDB.4.0&quot; userName=&quot;&quot;  password=&quot;&quot;
        ///		connectionString=&quot;&quot;
        ///       cmndTimeOut=&quot;60&quot;&gt;
        ///      &lt;summaryQuery useSP=&quot;False&quot; returnValueIsNumber=&quot;True&quot; returnValueInverted=&quot;False&quot;
        ///                  warningValue=&quot;1&quot; errorValue=&quot;2&quot; successValue=&quot;[any]&quot;
        ///                  useRowCountAsValue=&quot;False&quot; useExecuteTimeAsValue=&quot;False&quot;&gt;select * from SomeTable&lt;/summaryQuery&gt;
        ///      &lt;detailQuery useSP=&quot;False&quot;&gt;select * from SomeTable&lt;/d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OLEDBQueryCollectorDefaultConfig {
            get {
                return ResourceManager.GetString("OLEDBQueryCollectorDefaultConfig", resourceCulture);
            }
        }
    }
}
