//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickMon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [QuickMon]
        ///GO
        ///CREATE TABLE [dbo].[States](
        ///	[StateId] [tinyint] NOT NULL,
        ///	[Description] [nvarchar](50) NOT NULL,
        /// CONSTRAINT [PK_States] PRIMARY KEY CLUSTERED 
        ///(
        ///	[StateId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///GO
        ///CREATE TABLE [dbo].[AlertLevels](
        ///	[AlertLevel] [tinyint] NOT NULL,
        ///	[Description] [nvarchar](50) NOT NULL,
        /// CONSTRAINT [PK_AlertLevels] PRIMARY KEY CLUSTERED         /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleSqlDatabaseCreateScript {
            get {
                return ResourceManager.GetString("ExampleSqlDatabaseCreateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT top(@top) 
        ///	[InsertDate],
        ///	[AlertLevel],
        ///	[CollectorType],
        ///	[Category],
        ///	[PreviousState],
        ///	[CurrentState],
        ///	[Details]
        ///FROM
        ///	[AlertMessages]
        ///WHERE 
        ///	[InsertDate] between @FromDate and @ToDate and
        ///	(@AlertLevel is null or [AlertLevel] &gt;= @AlertLevel) and
        ///	(@CollectorType is null or [CollectorType] like @CollectorType) and
        ///	(@Category is null or [Category] like @Category) and
        ///	(@CurrentState is null or [CurrentState] = @CurrentState) and
        ///	(@Details is null or [Details] like @Details)
        ///OR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryTemplate {
            get {
                return ResourceManager.GetString("QueryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use master
        ///declare @PageSize varchar(10)
        ///select @PageSize=v.low/1024.0
        ///from master..spt_values v
        ///where v.number=1 and v.type=&apos;E&apos;
        ///
        ///select name as DatabaseName, convert(float,null) as Size
        ///into #tem
        ///From sysdatabases where dbid&gt;4 and name like &apos;&lt;Database&gt;&apos;
        ///
        ///declare @SQL varchar (8000)
        ///set @SQL=&apos;&apos;
        ///
        ///while exists (select * from #tem where size is null)
        ///begin
        ///select @SQL=&apos;update #tem set size=(select round(sum(size)*&apos;+@PageSize+&apos;/1024,0) From &apos;+quotename(databasename)+&apos;.dbo.sysfiles) where database [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectDatabaseSizesScript {
            get {
                return ResourceManager.GetString("SelectDatabaseSizesScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;config&gt;
        ///  &lt;connection sqlServer=&quot;&quot; database=&quot;&quot; integratedSec=&quot;True&quot; userName=&quot;&quot; password=&quot;&quot; &gt;
        ///    &lt;command cmndTimeOut=&quot;60&quot; useSP=&quot;True&quot; value=&quot;InsertMessage&quot; 
        ///             alertFieldName=&quot;AlertLevel&quot; 
        ///             collectorTypeFieldName=&quot;CollectorType&quot;
        ///             categoryFieldName=&quot;Category&quot;
        ///             previousStateFieldName=&quot;PreviousState&quot;
        ///             currentStateFieldName=&quot;CurrentState&quot;
        ///             detailsFieldName=&quot;Details&quot;
        ///             useSPForViewer=&quot;True&quot;
        ///             viewer=&quot;QueryMe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlDatabaseNotifierDefaultConfig {
            get {
                return ResourceManager.GetString("SqlDatabaseNotifierDefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;config&gt;  
        ///    &lt;databases&gt;
        ///      &lt;!--
        ///      &lt;database server=&quot;.&quot; name=&quot;master&quot; integratedSec=&quot;True&quot; userName=&quot;&quot;  password=&quot;&quot;&gt;
        ///        &lt;table  name=&quot;sometable&quot; warningValue=&quot;1&quot; errorValue=&quot;2&quot; /&gt;
        ///      &lt;/database&gt;
        ///      --&gt;      
        ///    &lt;/databases&gt;  
        ///&lt;/config&gt;.
        /// </summary>
        internal static string SqlDatabaseSizeCollectorDefaultConfig {
            get {
                return ResourceManager.GetString("SqlDatabaseSizeCollectorDefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;config&gt;
        ///  &lt;queries&gt;
        ///    &lt;!--
        ///    &lt;query name=&quot;&quot; sqlServer=&quot;.&quot; database=&quot;master&quot; integratedSec=&quot;True&quot; userName=&quot;&quot;  password=&quot;&quot;
        ///      usePersistentConnection=&quot;False&quot; applicationName=&quot;QuickMon&quot;
        ///       cmndTimeOut=&quot;60&quot;&gt;
        ///      &lt;summaryQuery useSP=&quot;False&quot; returnValueIsNumber=&quot;True&quot; returnValueInverted=&quot;False&quot;
        ///                  warningValue=&quot;1&quot; errorValue=&quot;2&quot; successValue=&quot;[any]&quot;
        ///                  useRowCountAsValue=&quot;False&quot; useExecuteTimeAsValue=&quot;False&quot;&gt;select * from SomeTable&lt;/summaryQuery&gt;
        ///      &lt;detai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlQueryCollectorDefaultConfig {
            get {
                return ResourceManager.GetString("SqlQueryCollectorDefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en-za&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;QuickMon SQL Query Collector tips&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    body 
        ///    {
        ///        font-family: Verdana;
        ///        font-size: 12;
        ///    }
        ///    h1, h2
        ///    {
        ///        color: Maroon;
        ///    }
        ///    a
        ///    {
        ///        text-decoration: none;
        ///    }
        ///    a:hover
        ///    {
        ///        text-decoration: underline:
        ///    }
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;QuickMon SQL Query Collector&lt;/h1&gt;
        ///&lt;p&gt;The &lt;a href=&quot;http://quickmon.codeplex.com&quot; target=&quot;_bla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLQueryTips {
            get {
                return ResourceManager.GetString("SQLQueryTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;config&gt;  
        ///    &lt;databases&gt;
        ///      &lt;!--
        ///      &lt;database server=&quot;.&quot; name=&quot;master&quot; integratedSec=&quot;True&quot; userName=&quot;&quot;  password=&quot;&quot; warningValueMB=&quot;1024&quot; errorValueMB=&quot;4096&quot; /&gt;
        ///      --&gt;      
        ///    &lt;/databases&gt;  
        ///&lt;/config&gt;.
        /// </summary>
        internal static string SqlTableSizeCollectorDefaultConfig {
            get {
                return ResourceManager.GetString("SqlTableSizeCollectorDefaultConfig", resourceCulture);
            }
        }
    }
}
