//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickMon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;config&gt;
        ///  &lt;rssConfig title=&quot;QuickMon RSS alerts&quot; link=&quot;&quot; description=&quot;&quot; language=&quot;en-us&quot; pubDate=&quot;&quot; generator=&quot;QuickMon RSS notifier&quot;
        ///             keepEntriesDays=&quot;10&quot;
        ///             lineTitle=&quot;%AlertLevel% - %CurrentState%&quot; 
        ///             lineCategory=&quot;%CollectorName%&quot; 
        ///             lineComments=&quot;%CollectorType%&quot; 
        ///             lineDescription=&quot;%Details%&quot;/&gt;
        ///&lt;/config&gt;.
        /// </summary>
        internal static string RSSFeedConfigTemplate_xml {
            get {
                return ResourceManager.GetString("RSSFeedConfigTemplate.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;item&gt;
        ///    &lt;title&gt;ThaTitle&lt;/title&gt;
        ///    &lt;!--&lt;link&gt;ALink&lt;/link&gt;--&gt;
        ///    &lt;guid&gt;ThaGuid&lt;/guid&gt;
        ///    &lt;pubDate&gt;ThaDate&lt;/pubDate&gt;
        ///    &lt;category&gt;ThaCategory&lt;/category&gt;
        ///    &lt;comments&gt;ThaComment&lt;/comments&gt;
        ///    &lt;description&gt;[CDATA[ TheDescription ]]&lt;/description&gt;
        ///&lt;/item&gt;.
        /// </summary>
        internal static string RSSFeedLineItem_xml {
            get {
                return ResourceManager.GetString("RSSFeedLineItem.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot;&gt;
        ///  &lt;channel&gt;
        ///    &lt;title&gt;QuickMon RSS 2.0 Feed&lt;/title&gt;
        ///    &lt;link&gt;http://www.example.com/&lt;/link&gt;
        ///    &lt;description&gt;QuickMon alert feed&lt;/description&gt;
        ///    &lt;lastBuildDate&gt;Mon, 12 Sep 2005 18:37:00 GMT&lt;/lastBuildDate&gt;
        ///    &lt;language&gt;en-us&lt;/language&gt;
        ///    &lt;Generator&gt;QuickMon RSS notifiers&lt;/Generator&gt;.
        /// </summary>
        internal static string RSSFeedTemplate_xml {
            get {
                return ResourceManager.GetString("RSSFeedTemplate.xml", resourceCulture);
            }
        }
    }
}
