//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowMenuOnStart {
            get {
                return ((bool)(this["ShowMenuOnStart"]));
            }
            set {
                this["ShowMenuOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainFormSnap {
            get {
                return ((bool)(this["MainFormSnap"]));
            }
            set {
                this["MainFormSnap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewVersion {
            get {
                return ((bool)(this["NewVersion"]));
            }
            set {
                this["NewVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ConcurrencyLevel {
            get {
                return ((int)(this["ConcurrencyLevel"]));
            }
            set {
                this["ConcurrencyLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int PollFrequencySec {
            get {
                return ((int)(this["PollFrequencySec"]));
            }
            set {
                this["PollFrequencySec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentQMConfigFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentQMConfigFiles"]));
            }
            set {
                this["RecentQMConfigFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainWindowLocation"]));
            }
            set {
                this["MainWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MainWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MainWindowSize"]));
            }
            set {
                this["MainWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutosaveChanges {
            get {
                return ((bool)(this["AutosaveChanges"]));
            }
            set {
                this["AutosaveChanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection KnownRemoteHosts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KnownRemoteHosts"]));
            }
            set {
                this["KnownRemoteHosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverridesMonitorPackFrequency {
            get {
                return ((bool)(this["OverridesMonitorPackFrequency"]));
            }
            set {
                this["OverridesMonitorPackFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateBackupOnSave {
            get {
                return ((bool)(this["CreateBackupOnSave"]));
            }
            set {
                this["CreateBackupOnSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationMasterKey {
            get {
                return ((string)(this["ApplicationMasterKey"]));
            }
            set {
                this["ApplicationMasterKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationUserNameCacheFilePath {
            get {
                return ((string)(this["ApplicationUserNameCacheFilePath"]));
            }
            set {
                this["ApplicationUserNameCacheFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ApplicationUserNameCache {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ApplicationUserNameCache"]));
            }
            set {
                this["ApplicationUserNameCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMonitorPack {
            get {
                return ((string)(this["LastMonitorPack"]));
            }
            set {
                this["LastMonitorPack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableAutoAdminMode {
            get {
                return ((bool)(this["DisableAutoAdminMode"]));
            }
            set {
                this["DisableAutoAdminMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string RecentQMConfigFileFilters {
            get {
                return ((string)(this["RecentQMConfigFileFilters"]));
            }
            set {
                this["RecentQMConfigFileFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFullPathForQuickRecentList {
            get {
                return ((bool)(this["ShowFullPathForQuickRecentList"]));
            }
            set {
                this["ShowFullPathForQuickRecentList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseTemplatesForNewObjects {
            get {
                return ((bool)(this["UseTemplatesForNewObjects"]));
            }
            set {
                this["UseTemplatesForNewObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int MainWindowTreeViewExtraColumnSize {
            get {
                return ((int)(this["MainWindowTreeViewExtraColumnSize"]));
            }
            set {
                this["MainWindowTreeViewExtraColumnSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowTreeViewExtraColumnTextAlign {
            get {
                return ((int)(this["MainWindowTreeViewExtraColumnTextAlign"]));
            }
            set {
                this["MainWindowTreeViewExtraColumnTextAlign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableAutoRefreshCollectorDetailAutomatically {
            get {
                return ((bool)(this["EnableAutoRefreshCollectorDetailAutomatically"]));
            }
            set {
                this["EnableAutoRefreshCollectorDetailAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\Hen IT\\QuickMon 5\\Scripts")]
        public string ScriptRepositoryDirectory {
            get {
                return ((string)(this["ScriptRepositoryDirectory"]));
            }
            set {
                this["ScriptRepositoryDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SortQuickRecentList {
            get {
                return ((bool)(this["SortQuickRecentList"]));
            }
            set {
                this["SortQuickRecentList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWindowCollectorQuickToolbarVisible {
            get {
                return ((bool)(this["MainWindowCollectorQuickToolbarVisible"]));
            }
            set {
                this["MainWindowCollectorQuickToolbarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseFrequentJumpList {
            get {
                return ((bool)(this["UseFrequentJumpList"]));
            }
            set {
                this["UseFrequentJumpList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableRawEditing {
            get {
                return ((bool)(this["EnableRawEditing"]));
            }
            set {
                this["EnableRawEditing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection GraphLineColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GraphLineColors"]));
            }
            set {
                this["GraphLineColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GraphBackgroundColor1 {
            get {
                return ((global::System.Drawing.Color)(this["GraphBackgroundColor1"]));
            }
            set {
                this["GraphBackgroundColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color GraphBackgroundColor2 {
            get {
                return ((global::System.Drawing.Color)(this["GraphBackgroundColor2"]));
            }
            set {
                this["GraphBackgroundColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color GraphGridColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphGridColor"]));
            }
            set {
                this["GraphGridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GraphAxisLabelsColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphAxisLabelsColor"]));
            }
            set {
                this["GraphAxisLabelsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color GraphSelectionBarColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphSelectionBarColor"]));
            }
            set {
                this["GraphSelectionBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GraphDefaultType {
            get {
                return ((int)(this["GraphDefaultType"]));
            }
            set {
                this["GraphDefaultType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int GraphGradientDirection {
            get {
                return ((int)(this["GraphGradientDirection"]));
            }
            set {
                this["GraphGradientDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GraphClosestClickedValueType {
            get {
                return ((int)(this["GraphClosestClickedValueType"]));
            }
            set {
                this["GraphClosestClickedValueType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GraphClosestClickedValueColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphClosestClickedValueColor"]));
            }
            set {
                this["GraphClosestClickedValueColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GraphHeaderVisible {
            get {
                return ((bool)(this["GraphHeaderVisible"]));
            }
            set {
                this["GraphHeaderVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GraphLegendVisible {
            get {
                return ((bool)(this["GraphLegendVisible"]));
            }
            set {
                this["GraphLegendVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GraphHorisontalGridLinesVisible {
            get {
                return ((bool)(this["GraphHorisontalGridLinesVisible"]));
            }
            set {
                this["GraphHorisontalGridLinesVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GraphVerticalGridLinesVisible {
            get {
                return ((bool)(this["GraphVerticalGridLinesVisible"]));
            }
            set {
                this["GraphVerticalGridLinesVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GraphSelectionBarVisible {
            get {
                return ((bool)(this["GraphSelectionBarVisible"]));
            }
            set {
                this["GraphSelectionBarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GraphHighlightClickedSeriesVisible {
            get {
                return ((bool)(this["GraphHighlightClickedSeriesVisible"]));
            }
            set {
                this["GraphHighlightClickedSeriesVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GraphEnableFillAreaBelowSeries {
            get {
                return ((bool)(this["GraphEnableFillAreaBelowSeries"]));
            }
            set {
                this["GraphEnableFillAreaBelowSeries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public int GraphFillAreaBelowSeriesAlpha {
            get {
                return ((int)(this["GraphFillAreaBelowSeriesAlpha"]));
            }
            set {
                this["GraphFillAreaBelowSeriesAlpha"] = value;
            }
        }
    }
}
